
server:
  port: 7777
  
#eureka:
# client: 
#  serviceUrl:
#   defaultZone: http://192.168.1.155:8089/eureka
#     
spring :
  datasource :
#   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
    
    